### ISSUE TITLE
Open document

### ISSUE THREAD

**Issue by mariusblarsen** [Agnar22/Kundestyrt2020-NAV-DIPS#1]
**What**
Back log item with ID = 1.
Create a basic React Web App, and show that it is in fact running. 

**Why**
To have a good starting point for building our final web app.

**How**
By downloading Node and npm/npx, and running "npx create-react-app", and remove any useless parts from the example project.
If we have access to a DIPS Arena clone the web app can be rendered inside the iframe of the Arena clone.

- [x] Download Node and npm.
- [x] Create React app.
- [x] Remove unwanted parts from the example project.
- [x] Build into docker container
- [x] Update readme

**Comment by hexxunset** [comment]
PR: https://github.com/Agnar22/Kundestyrt2020-NAV-DIPS/pull/12

Merk at flere commits ikke inneholder id for issue, da det ble foretatt litt sandboxing for designmanual. Design er satt på vent, og det vil dukke opp et eget issue på dette.
